Implemented the open ended question and modified some other files
OmarAgamy9/SurveyMonkey4806 pull request #40
Opened 2022-03-24 18:44 UTC by TaherShabaan99

2022-03-24 18:50 UTC, hassanidea reviewed
Why have you removed QText and Qtype files?

2022-03-24 18:56 UTC, OmarAgamy9 approved these changes
Looks good to me

2022-03-24 19:19 UTC, Dez1999 commented
Looks good! Good structure and variable names. Just check that the tests are running properly

2022-03-29 18:16 UTC, keving3ng requested changes

2022-03-29 18:16 UTC, keving3ng commented on src/main/java/com/SurveyMonkey/model/questions/types/QuestionType.java
> +    protected int number;
id != number, should add another id field

2022-03-29 18:16 UTC, keving3ng commented on src/main/java/com/SurveyMonkey/model/questions/types/QuestionType.java
> +    public int getId() {
update to reflect number/id change

2022-04-01 02:37 UTC, closed without merging