Added testing to MC Questions
OmarAgamy9/SurveyMonkey4806 pull request #50
Opened 2022-03-30 19:06 UTC by OmarAgamy9

Added few tests for the MCQ's.
Changed the naming of the MCQ class to MCQModel

2022-03-31 19:52 UTC, keving3ng requested changes
the jars under lib/ that are in this branch should not be commited. please omit them in your gitignore and untrack them in git to remove

see this https://stackoverflow.com/questions/1274057/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitign

2022-03-31 19:52 UTC, keving3ng commented on src/main/java/com/SurveyMonkey/model/questions/Questions.java
> +abstract public class Questions {
There is already an abstract type called QType, this class was supposed to be what CreateSurvey is right now (a class to hold a list of questions).

2022-03-31 23:49 UTC, hassanidea commented on src/test/java/com/SurveyMonkey/TakerControllerTests.java
> +//package com.SurveyMonkey;
I will accept this pull request and I will make the changes necessary

2022-03-31 23:50 UTC, hassanidea approved these changes
Abstract class will be modified

2022-04-01 02:35 UTC, keving3ng approved these changes

2022-04-01 02:35 UTC, merged