Added SurveyorHome Page and changed results controller to RestController
OmarAgamy9/SurveyMonkey4806 pull request #82
Opened 2022-04-07 20:29 UTC by Dez1999

Continuing to work on making surveyorHome Page dynamic

2022-04-07 21:57 UTC, OmarAgamy9 requested changes
I am confused as to what's the use of surveyorHome

2022-04-07 22:00 UTC, hassanidea commented
Hey desmond, can you please make the connection between the surveyorHome and createSurvey.

2022-04-07 22:08 UTC, Dez1999 commented
@OmarAgamy9 SurveyorHome would allow the surveyor to have a general home page with the different surveys created. Let me know if there's anything that should be changed @hassanidea sounds good, just added it

2022-04-07 22:45 UTC, hassanidea approved these changes
Looks good to me now

2022-04-08 01:39 UTC, keving3ng commented on src/main/resources/templates/surveyorHome.html
> +            <script>
scripts should be placed outside of html but its fine for now

2022-04-08 01:39 UTC, keving3ng approved these changes

2022-04-08 02:33 UTC, TaherShabaan99 reviewed
I believe it needs more work to be done!

2022-04-08 12:19 UTC, OmarAgamy9 approved these changes
Looks good now

2022-04-08 12:19 UTC, merged